### ISSUE TITLE
workspace

### ISSUE THREAD

**Issue by AYB-cmd** [AYB-cmd/web-app#1]
n'oubliez pas l'installation et l'initialisation de votre environnement. @terbouchi @zinebaguennouz @AYB-cmd @amine-dope @BOUKRIM

**Comment by amine-dope** [comment]
Le travail est déjà fait

**Comment by zinebaguennouz** [comment]
l installation et déjà fait

**Comment by AYB-cmd** [comment]
deja fait

**Comment by BOUKRIM** [comment]
L'environnement est prepare .

**Comment by terbouchi** [comment]
j'ai fini :)
