### ISSUE TITLE
Header desktop

### ISSUE THREAD

**Issue by AYB-cmd** [AYB-cmd/web-app#16]
j'ai fini mon section  HEADER en attendant vos commentaires.
564712f

@terbouchi  @zinebaguennouz  @amine-dope  @BOUKRIM

**Comment by amine-dope** [comment]
we c'est tres bien et 
NOUS FONS CONFIANCE je pense plus petit

**Comment by terbouchi** [comment]
c'est très bien
2 remarques :  logo faut être centré
                        "Nous fons confiance" a l'agrandir svp
appart ça, tout est mangifique

**Comment by AYB-cmd** [comment]
j'ai fixé le logo et le bouton
5585799
@terbouchi

**Comment by BOUKRIM** [comment]
attention  la manque de hover

**Comment by AYB-cmd** [comment]
j'attends le design.
@BOUKRIM
