### ISSUE TITLE
Footer desktop

### ISSUE THREAD

**Issue by AYB-cmd** [AYB-cmd/web-app#20]
j'ai fini mon section Footer en attendant vos commentaires.
b6d6f66

@terbouchi @zinebaguennouz @amine-dope @BOUKRIM

**Comment by terbouchi** [comment]
1remarque:
les dernières phrases ( Copyright / www.youcode.ma / all right reserved / Classe 1) devront être en même font-size

**Comment by amine-dope** [comment]
pas mal
