### ISSUE TITLE
feauters

### ISSUE THREAD

**Issue by amine-dope** [AYB-cmd/web-app#6]
j'ai terminé partie feauters et je veux votre des opinions 8c065c7

**Comment by AYB-cmd** [comment]
n'oubliez pas d'inclure votre charte graphique @amine-dope  @BOUKRIM

**Comment by BOUKRIM** [comment]
Oui Bien Sur @AYB-cmd

**Comment by amine-dope** [comment]
d'accord @AYB-cmd
